spring.application.name=geminiAi2

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=privacy_policy

spring.redis.cloud.host=${REDIS_HOST}
spring.redis.cloud.port=${REDIS_PORT}
spring.redis.cloud.password=${REDIS_PASSWORD}

spring.ai.vectorstore.mongodb.collection-name=vector_store
spring.ai.vectorstore.mongodb.index-name=vector_index
spring.ai.vectorstore.mongodb.initialize-schema=false

logging.level.org.apache.pdfbox.pdmodel.font.FileSystemFontProvider=ERROR

spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3-flash-preview
spring.ai.google.genai.embedding.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.embedding.project-id=${GENAI_PROJECT_ID}
spring.ai.google.genai.embedding.location=us-central1
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.options.task-type=RETRIEVAL_DOCUMENT

spring.ai.google.genai.project-id=${GENAI_PROJECT_ID}
spring.ai.google.genai.location=us-central1